### ISSUE TITLE
The dependency Errors

### ISSUE THREAD

**Issue by manjubluemoon** [ladunjexa/reactjs18-3d-portfolio#10]
Hi Specialists,

When i run this code on Ubuntu 22.04 with all latest Node JS and 3 D elements, there is dependency errors

mg@venom06:~/Threejs_3D_Portfolio$ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: 3dfolio@0.0.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^15.0.0 || ^16.0.0-beta || ^16.0.0" from react-tilt@0.1.4
npm ERR! node_modules/react-tilt
npm ERR!   react-tilt@"^0.1.4" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /home/mg/.npm/_logs/2023-06-14T04_09_37_543Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mg/.npm/_logs/2023-06-14T04_09_37_543Z-debug-0.log

**Comment by ladunjexa** [comment]
Hi _manjubluemoon_,
Take a look at #2, if this doesn't solve the problem, don't hesitate to inform me :)

**Comment by manjubluemoon** [comment]
Excellent Support by ladunjexa!!!

**Comment by manjubluemoon** [comment]
Excellent Support by ladunjexa!!!
