### ISSUE TITLE
clone  not working 

### ISSUE THREAD

**Issue by baya-et** [ladunjexa/reactjs18-3d-portfolio#4]
clone this repo not working

**Comment by ladunjexa** [comment]
I missed adding `.git` in the desired line (***Getting Started, Installation, Step 1***).
To clone this repo use this web url ` https://github.com/ladunjexa/Threejs_3D_Portfolio.git`.

In any repository, press the green `code` button and there you can learn about how-to clone (via HTTPS, SSH or GitHub CLI).
